/**
 * Typed view over timeline-lf.json - single source of truth generated by
 * scripts/build_timeline_lf.py, also consumed by scripts/gen_audio_lf.py so
 * SFX cues cannot drift from visual cuts. Same pattern as the reel's
 * src/data/timeline.ts.
 */
import raw from './timeline-lf.json';

export type LFShotMode = 'full' | 'hero' | 'split' | 'hero-crop' | 'duo' | 'triad' | 'quad' | 'quad-range' | 'montage';
export type LFOverlay = 'rigidity' | 'directivity' | 'eqsteps' | 'phase' | 'crossover';

export interface LFShot {
  from: number;
  dur: number;
  mode: LFShotMode;
  img: string[];
  labels?: string[];
  overlay?: LFOverlay;
  move?: string;
  sfx: string;
  text?: string | null;
}

export interface LFChapterData {
  id: string;
  from: number;
  dur: number;
  shots: LFShot[];
  product?: 'srp350' | 'srp400' | 'srp501' | 'srp601' | 'slf210';
  rowFrames?: number[];
  familyFrame?: number;
}

export interface LFTimeline {
  fps: number;
  width: number;
  height: number;
  durationInFrames: number;
  chapters: LFChapterData[];
  cues: {frame: number; sfx: string; chapter: string; gain: number}[];
  coverage: {primary: string[]};
}

export const TIMELINE_LF = raw as unknown as LFTimeline;
