/**
 * Typed view over timeline.json - the single source of truth generated by
 * scripts/build_timeline.py and also consumed by scripts/gen_audio.py, so the
 * SFX cues can never drift from the visual cuts.
 */
import raw from './timeline.json';
import type {ProductKey} from './products';

export type ShotMode =
  | 'hero'
  | 'hero-crop'
  | 'panel'
  | 'duo'
  | 'triad'
  | 'quad-dna'
  | 'quad-range';

export type Move =
  | 'push'
  | 'pull'
  | 'driftL'
  | 'driftR'
  | 'slideUp'
  | 'slideL'
  | 'fan'
  | 'dolly-tweeter'
  | 'dolly-eq';

export type Overlay = 'rigidity' | 'directivity' | 'eqsteps' | 'phase' | 'crossover';

export interface Shot {
  from: number;
  dur: number;
  mode: ShotMode;
  img: string[];
  labels?: string[];
  sfx: string;
  move?: Move;
  overlay?: Overlay;
  text?: string;
  tier: 'primary';
}

export interface AmbientShot {
  img: string;
  band: 'top' | 'bottom';
  from: number;
  dur: number;
}

export interface Scene {
  id: string;
  from: number;
  dur: number;
  kind: 'hook' | 'dna' | 'product' | 'system' | 'pricing' | 'cta';
  product?: ProductKey;
  shots: Shot[];
  ambient: AmbientShot[];
  rowFrames?: number[];
}

export interface Timeline {
  fps: number;
  width: number;
  height: number;
  durationInFrames: number;
  safe: {top: number; bottom: number; side: number};
  scenes: Scene[];
  cues: {frame: number; sfx: string; scene: string; gain: number}[];
  coverage: {primary: string[]; ambient: string[]};
}

export const TIMELINE = raw as unknown as Timeline;

export const imgSrc = (slug: string) => `img/${slug}.webp`;
